name: Playwright

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPATCH_INTEGRATION_MODE: mock
      REPATCH_SUPABASE_MODE: mock
      REPATCH_SUPABASE_SEED: tests/fixtures/supabase-seed.json
      REPATCH_DISABLE_VIDEO_RENDER: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Next.js app
        run: bun run build

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        run: bun run test:e2e:ci

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          if-no-files-found: ignore
