name: Playwright

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start -x studio,inbucket,pgadmin,imgproxy,logflare,vector

      - name: Export Supabase credentials
        shell: bash
        run: |
          set -a
          if [ -f ./.supabase/.env ]; then
            source ./.supabase/.env
          elif [ -f ./.supabase/docker/.env ]; then
            source ./.supabase/docker/.env
          fi
          set +a
          echo "NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}" >> "$GITHUB_ENV"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" >> "$GITHUB_ENV"
          echo "SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: bun install

      - name: Apply database migrations
        run: supabase db reset

      - name: Seed baseline data
        run: bun run db:seed

      - name: Install Playwright browsers
        run: bun run test:e2e:install

      - name: Run Playwright suite
        env:
          NEXT_PUBLIC_APP_URL: http://127.0.0.1:3000
          INTEGRATION_MODE: mock
          SKIP_DB_SEED: "1"
        run: bun run ci:test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-artifacts
          retention-days: 7
